#include "exportpointcloud.h"
#include "buildmesh.h"
#include "parammodeler_dock.h"

#include <QFile>
#include <QMatrix4x4>
#include <QMessageBox>
#include <QTextStream>
#include <QVector3D>
#include <QtMath>
#include <cstdlib>

// ============================================================
// 对单个三角形用重心坐标随机采一个点
// ============================================================
static QVector3D sampleTriangle( const QVector3D &A,
                                  const QVector3D &B,
                                  const QVector3D &C )
{
    float r1 = float( qrand() ) / RAND_MAX;
    float r2 = float( qrand() ) / RAND_MAX;
    float sqr1 = qSqrt( r1 );
    return ( 1.0f - sqr1 ) * A
         + sqr1 * ( 1.0f - r2 ) * B
         + sqr1 * r2 * C;
}

// ============================================================
// 计算三角形面积
// ============================================================
static float triangleArea( const QVector3D &A,
                            const QVector3D &B,
                            const QVector3D &C )
{
    return QVector3D::crossProduct( B - A, C - A ).length() * 0.5f;
}

static QVector3D applyPose( const QVector3D &v,
                             double tx, double ty, double tz,
                             double rx, double ry, double rz )
{
    QMatrix4x4 mat;
    mat.setToIdentity();
    mat.translate( tx, ty, tz );
    mat.rotate( rx, 1, 0, 0 ); // ω
    mat.rotate( ry, 0, 1, 0 ); // φ
    mat.rotate( rz, 0, 0, 1 ); // κ
    return mat.map( v );
}

// ============================================================
// 主函数
// ============================================================
bool ExportPointCloud::exportPLY( const QString    &fileName,
                                   const QString    &primitiveType,
                                   ParamModelerDock *dock,
                                   int               sampleCount )
{
    // 1. 生成网格
    MeshData mesh = BuildMesh::build( primitiveType, dock );
    if ( mesh.isEmpty() )
    {
        QMessageBox::warning( nullptr, "警告",
            QString("基元 \"%1\" 暂不支持导出。").arg( primitiveType ) );
        return false;
    }

    // 2. 计算每个三角形的面积，累积权重
    int triCount = mesh.indices.size() / 3;
    QVector<float> areas( triCount );
    float totalArea = 0.0f;

    for ( int i = 0; i < triCount; i++ )
    {
        QVector3D A = mesh.vertices[ mesh.indices[i*3]   ];
        QVector3D B = mesh.vertices[ mesh.indices[i*3+1] ];
        QVector3D C = mesh.vertices[ mesh.indices[i*3+2] ];
        areas[i] = triangleArea( A, B, C );
        totalArea += areas[i];
    }

    if ( totalArea <= 0 )
    {
        QMessageBox::warning( nullptr, "警告", "网格面积为零，无法采样。" );
        return false;
    }

    // 3. 按面积加权采样
    // 读取位姿参数
    double tx = dock->poseTranslateX();
    double ty = dock->poseTranslateY();
    double tz = dock->poseTranslateZ();
    double rx = dock->poseRotateX();
    double ry = dock->poseRotateY();
    double rz = dock->poseRotateZ();
    bool hasPose = ( tx!=0||ty!=0||tz!=0||rx!=0||ry!=0||rz!=0 );

    QVector<QVector3D> points;
    points.reserve( sampleCount );

    // 构建累积面积数组，用于按权重随机选三角形
    QVector<float> cumArea( triCount );
    cumArea[0] = areas[0];
    for ( int i = 1; i < triCount; i++ )
        cumArea[i] = cumArea[i-1] + areas[i];

    for ( int s = 0; s < sampleCount; s++ )
    {
        // 按面积权重随机选一个三角形（二分查找）
        float r = float( qrand() ) / RAND_MAX * totalArea;
        int lo = 0, hi = triCount - 1;
        while ( lo < hi )
        {
            int mid = ( lo + hi ) / 2;
            if ( cumArea[mid] < r ) lo = mid + 1;
            else hi = mid;
        }

        QVector3D A = mesh.vertices[ mesh.indices[lo*3]   ];
        QVector3D B = mesh.vertices[ mesh.indices[lo*3+1] ];
        QVector3D C = mesh.vertices[ mesh.indices[lo*3+2] ];

        QVector3D pt = sampleTriangle( A, B, C );
        if ( hasPose )
            pt = applyPose( pt, tx, ty, tz, rx, ry, rz );

        points << pt;
    }

    // 4. 写 PLY 文件（ASCII 格式）
    QFile file( fileName );
    if ( !file.open( QIODevice::WriteOnly | QIODevice::Text ) )
    {
        QMessageBox::critical( nullptr, "错误", "无法写入 PLY 文件!" );
        return false;
    }

    QTextStream out( &file );
    // PLY header
    out << "ply\n";
    out << "format ascii 1.0\n";
    out << "comment generated by ParamModeler\n";
    out << "element vertex " << points.size() << "\n";
    out << "property float x\n";
    out << "property float y\n";
    out << "property float z\n";
    out << "end_header\n";

    // 顶点数据
    for ( const QVector3D &p : points )
        out << p.x() << " " << p.y() << " " << p.z() << "\n";

    file.close();
    return true;
}
