#include "exportobj.h"
#include "buildmesh.h"
#include "parammodeler_dock.h"
#include <QFile>
#include <QMap>
#include <QMatrix4x4>
#include <QMessageBox>
#include <QTextStream>
#include <QVector3D>
#include <QtMath>

// ============================================================
// 顶点去重
// ============================================================
static void deduplicateMesh( const MeshData &mesh,
                             QVector<QVector3D> &uniqueVerts,
                             QVector<int>       &faceIndices )
{
    QMap<QString, int> vertMap;
    uniqueVerts.clear();
    faceIndices.clear();
    const int scale = 10000;
    for ( int i = 0; i < mesh.indices.size(); i++ )
    {
        const QVector3D &v = mesh.vertices[ mesh.indices[i] ];
        QString key = QString("%1_%2_%3")
            .arg( qRound( v.x() * scale ) )
            .arg( qRound( v.y() * scale ) )
            .arg( qRound( v.z() * scale ) );
        if ( vertMap.contains( key ) )
            faceIndices << vertMap[key];
        else {
            int idx = uniqueVerts.size();
            vertMap[key] = idx;
            uniqueVerts << v;
            faceIndices << idx;
        }
    }
}

// ============================================================
// 位姿变换：ZYX 欧拉角（角度制）+ 平移
// 顺序：先旋转（Z→Y→X），再平移
// ============================================================
static QVector3D applyPose( const QVector3D &v,
                            double tx, double ty, double tz,
                            double rx, double ry, double rz )
{
    QMatrix4x4 mat;
    mat.setToIdentity();
    mat.translate( tx, ty, tz );
    mat.rotate( rz, 0, 0, 1 );  // 先绕 Z
    mat.rotate( ry, 0, 1, 0 );  // 再绕 Y
    mat.rotate( rx, 1, 0, 0 );  // 最后绕 X
    return mat.map( v );
}

// ============================================================
// 主导出函数
// ============================================================
bool ExportOBJ::exportOBJ( const QString    &fileName,
                            const QString    &primitiveType,
                            ParamModelerDock *dock )
{
    // 1. 生成网格
    MeshData mesh = BuildMesh::build( primitiveType, dock );
    if ( mesh.isEmpty() )
    {
        QMessageBox::warning( nullptr, "警告",
            QString("基元 \"%1\" 暂不支持导出。").arg( primitiveType ) );
        return false;
    }

    // 2. 顶点去重
    QVector<QVector3D> verts;
    QVector<int>       indices;
    deduplicateMesh( mesh, verts, indices );

    // 3. 读取位姿参数
    double tx = dock->poseTranslateX();
    double ty = dock->poseTranslateY();
    double tz = dock->poseTranslateZ();
    double rx = dock->poseRotateX();
    double ry = dock->poseRotateY();
    double rz = dock->poseRotateZ();

    bool hasPose = ( tx != 0 || ty != 0 || tz != 0 ||
                     rx != 0 || ry != 0 || rz != 0 );

    // 4. 写 OBJ 文件
    QFile file( fileName );
    if ( !file.open( QIODevice::WriteOnly | QIODevice::Text ) )
    {
        QMessageBox::critical( nullptr, "错误", "无法写入 OBJ 文件!" );
        return false;
    }

    QTextStream out( &file );
    out << "# OBJ file generated by ParamModeler\n";
    out << "# Primitive: " << primitiveType << "\n";
    if ( hasPose )
        out << "# Pose: tx=" << tx << " ty=" << ty << " tz=" << tz
            << " rx=" << rx << " ry=" << ry << " rz=" << rz << "\n";
    out << "# Vertices: " << verts.size()
        << "  Triangles: " << ( indices.size() / 3 ) << "\n\n";

    // 顶点（应用位姿变换）
    for ( const QVector3D &v : verts )
    {
        QVector3D vt = hasPose ? applyPose( v, tx, ty, tz, rx, ry, rz ) : v;
        out << "v " << vt.x() << " " << vt.y() << " " << vt.z() << "\n";
    }
    out << "\n";

    // 面
    for ( int i = 0; i + 2 < indices.size(); i += 3 )
        out << "f " << indices[i]+1
            << " "  << indices[i+1]+1
            << " "  << indices[i+2]+1 << "\n";

    file.close();
    return true;
}