/***************************************************************************
  parammodeler_export.cpp
  OBJ / JSON model export
  -------------------
         begin                : July 2026
         copyright            : (C) 2026 by Chai
         email                : 2080673411@qq.com
 ***************************************************************************/

#include "parammodeler_export.h"
#include "buildmesh.h"
#include "parammodeler_dock.h"
#include "ui_parammodeler_dock.h"

#include <QFile>
#include <QFileDialog>
#include <QJsonDocument>
#include <QMap>
#include <QMatrix4x4>
#include <QMessageBox>
#include <QTextStream>
#include <QVector3D>
#include <QtMath>

// ============================================================
// 共享工具
// ============================================================

// TODO: deduplicate with exportpointcloud.cpp (same applyPose)
static QVector3D applyPose( const QVector3D &v,
                            double tx, double ty, double tz,
                            double rx, double ry, double rz )
{
    QMatrix4x4 mat;
    mat.setToIdentity();
    mat.translate( tx, ty, tz );
    mat.rotate( rx, 1, 0, 0 );
    mat.rotate( ry, 0, 1, 0 );
    mat.rotate( rz, 0, 0, 1 );
    return mat.map( v );
}

// ============================================================
// OBJ
// ============================================================

static void deduplicateMesh( const MeshData &mesh,
                             QVector<QVector3D> &uniqueVerts,
                             QVector<int>       &faceIndices )
{
    QMap<QString, int> vertMap;
    uniqueVerts.clear();
    faceIndices.clear();
    const int scale = 10000;
    for ( int i = 0; i < mesh.indices.size(); i++ )
    {
        const QVector3D &v = mesh.vertices[ mesh.indices[i] ];
        QString key = QString("%1_%2_%3")
            .arg( qRound( v.x() * scale ) )
            .arg( qRound( v.y() * scale ) )
            .arg( qRound( v.z() * scale ) );
        if ( vertMap.contains( key ) )
            faceIndices << vertMap[key];
        else {
            int idx = uniqueVerts.size();
            vertMap[key] = idx;
            uniqueVerts << v;
            faceIndices << idx;
        }
    }
}

bool ExportOBJ::exportOBJ( const QString    &fileName,
                            const QString    &primitiveType,
                            ParamModelerDock *dock )
{
    MeshData mesh = BuildMesh::build( primitiveType, dock );
    if ( mesh.isEmpty() )
    {
        QMessageBox::warning( nullptr, "警告",
            QString("基元 \"%1\" 暂不支持导出。").arg( primitiveType ) );
        return false;
    }

    QVector<QVector3D> verts;
    QVector<int>       indices;
    deduplicateMesh( mesh, verts, indices );

    double tx = dock->poseTranslateX();
    double ty = dock->poseTranslateY();
    double tz = dock->poseTranslateZ();
    double rx = dock->poseRotateX();
    double ry = dock->poseRotateY();
    double rz = dock->poseRotateZ();

    bool hasPose = ( tx != 0 || ty != 0 || tz != 0 ||
                     rx != 0 || ry != 0 || rz != 0 );

    QFile file( fileName );
    if ( !file.open( QIODevice::WriteOnly | QIODevice::Text ) )
    {
        QMessageBox::critical( nullptr, "错误", "无法写入 OBJ 文件!" );
        return false;
    }

    QTextStream out( &file );
    out << "# OBJ file generated by ParamModeler\n";
    out << "# Primitive: " << primitiveType << "\n";
    if ( hasPose )
        out << "# Pose: tx=" << tx << " ty=" << ty << " tz=" << tz
            << " rx=" << rx << " ry=" << ry << " rz=" << rz << "\n";
    out << "# Vertices: " << verts.size()
        << "  Triangles: " << ( indices.size() / 3 ) << "\n\n";

    for ( const QVector3D &v : verts )
    {
        QVector3D vt = hasPose ? applyPose( v, tx, ty, tz, rx, ry, rz ) : v;
        out << "v " << vt.x() << " " << vt.y() << " " << vt.z() << "\n";
    }
    out << "\n";

    for ( int i = 0; i + 2 < indices.size(); i += 3 )
        out << "f " << indices[i]+1
            << " "  << indices[i+1]+1
            << " "  << indices[i+2]+1 << "\n";

    file.close();
    return true;
}

// ============================================================
// JSON
// ============================================================

bool ExportJSON::writeJSON( ParamModelerDock *dock )
{
    QString fileName = QFileDialog::getSaveFileName(
        dock, QObject::tr("保存 JSON 文件"), "", QObject::tr("JSON Files (*.json)")
    );

    if ( fileName.isEmpty() )
        return false;

    QFile file( fileName );
    if ( !file.open( QIODevice::WriteOnly | QIODevice::Text ) )
    {
        QMessageBox::critical( dock, QObject::tr("错误"), QObject::tr("无法写入文件！") );
        return false;
    }

    QString primitiveType = dock->ui->comboPrimitive->currentText();

    QJsonObject root;
    root["type"] = primitiveType;
    root["transform"] = buildTransform( dock );
    root["params"] = buildParams( dock, primitiveType );

    QJsonDocument doc( root );
    file.write( doc.toJson( QJsonDocument::Indented ) );
    file.close();

    QMessageBox::information(
        dock,
        QObject::tr("导出成功"),
        QObject::tr("JSON 文件已保存到：\n%1").arg( fileName ) );

    return true;
}

QJsonObject ExportJSON::buildTransform( ParamModelerDock *dock )
{
    QJsonObject t;

    t["tx"] = dock->poseTranslateX();
    t["ty"] = dock->poseTranslateY();
    t["tz"] = dock->poseTranslateZ();
    t["rx"] = dock->poseRotateX();
    t["ry"] = dock->poseRotateY();
    t["rz"] = dock->poseRotateZ();

    return t;
}

QJsonObject ExportJSON::buildParams( ParamModelerDock *dock, const QString &type )
{
    QJsonObject p;

    if ( type == "Cuboid" )
    {
        p["length"]  = dock->cuboidLength();
        p["width"]  = dock->cuboidWidth();
        p["height"] = dock->cuboidHeight();
    }
    else if ( type == "Cylinder" )
    {
      p["radius"] = dock->cylinderRadius();
      p["height"] = dock->cylinderHeight();
    }
    else if ( type == "LHouse" )
    {
      p["totalLength"]    = dock->LTotalLength();
      p["wingRatio"]      = dock->LWingRatio();
      p["totalWidth"]     = dock->LTotalWidth();
      p["wingWidthRatio"] = dock->LWingWidthRatio();
      p["height"]         = dock->LHeight();
    }
    else if ( type == "ConeCylinder" )
    {
        p["radius"] = dock->coneCylRadius();
        const double cylH = dock->coneCylCylHeight();
        const double coneH = dock->coneCylConeHeight();
        const double totalH = cylH + coneH;
        p["totalHeight"] = totalH;
        p["cylinderRatio"] = totalH > 1e-6 ? cylH / totalH : 0.7;
    }
    else if ( type == "GabledRoof" )
    {
        p["length"] = dock->gabledRoofLength();
        p["width"] = dock->gabledRoofWidth();
        const double wallH = dock->gabledRoofWallHeight();
        const double roofH = dock->gabledRoofRoofHeight();
        const double totalH = wallH + roofH;
        p["totalHeight"] = totalH;
        p["wallRatio"] = totalH > 1e-6 ? wallH / totalH : 0.7;
    }
    else if ( type == "PyramidRoof" )
    {
        p["length"] = dock->pyramidLength();
        p["width"] = dock->pyramidWidth();
        const double wallH = dock->pyramidWallHeight();
        const double roofH = dock->pyramidRoofHeight();
        const double totalH = wallH + roofH;
        p["totalHeight"] = totalH;
        p["wallRatio"] = totalH > 1e-6 ? wallH / totalH : 0.7;
    }
    else if ( type == "TruncatedPyramidRoof" )
    {
      p["length"] = dock->tpBottomLength();
      p["width"] = dock->tpBottomWidth();
      const double wallH = dock->tpWallHeight();
      const double roofH = dock->tpRoofHeight();
      const double totalH = wallH + roofH;
      p["totalHeight"] = totalH;
      p["wallRatio"] = totalH > 1e-6 ? wallH / totalH : 0.7;
      p["topLength"] = dock->tpTopLength();
      p["topWidth"] = dock->tpTopWidth();
    }
    else if ( type == "HalfCylinderRoof" )
    {
        p["length"]      = dock->hcrLength();
        p["width"]      = dock->hcrWidth();
        p["wallHeight"] = dock->hcrWallHeight();
        p["radius"]     = dock->hcrRadius();
    }
    else if ( type == "CylinderDome" || type == "CylinderHemisphere" )
    {
      p["radius"]     = dock->cylHemiRadius();
      const double cylH = dock->cylHemiHeight();
      const double domeH = dock->cylHemiDomeHeight();
      const double totalH = cylH + domeH;
      p["totalHeight"] = totalH;
      p["cylinderRatio"] = totalH > 1e-6 ? cylH / totalH : 0.7;
      p["bulgeFactor"]= dock->cylHemiBulge();
    }
    else if ( type == "IndentedCuboid" )
    {
      p["outerLength"]  = dock->icOuterLength();
      p["outerWidth"]  = dock->icOuterWidth();
      p["outerHeight"] = dock->icOuterHeight();
      p["innerLength"]  = dock->icInnerLength();
      p["innerWidth"]  = dock->icInnerWidth();
      p["innerHeight"] = dock->icInnerHeight();
      p["offsetX"]     = dock->icOffsetX();
      p["offsetY"]     = dock->icOffsetY();
    }
    else if ( type == "AsymmetricGableHouse" )
    {
      p["length"]       = dock->aghLength();
      p["width"]       = dock->aghWidth();
      const double wallH = dock->aghWallHeight();
      const double roofH = dock->aghRoofHeight();
      const double totalH = wallH + roofH;
      p["totalHeight"]  = totalH;
      p["wallRatio"]  = totalH > 1e-6 ? wallH / totalH : 0.7;
      p["ridgeLength"] = dock->aghRidgeLength();
      p["ridgeOffset"] = dock->aghRidgeOffset();
      p["ridgeRatio"]  = dock->aghRidgeRatio();
    }
    else if ( type == "FourStageRoundTower" )
    {
      p["baseRadius"]     = dock->ftBaseRadius();
      p["baseHeight"]     = dock->ftBaseHeight();
      p["middleHeight"]   = dock->ftMiddleHeight();
      p["middleTopRadius"]= dock->ftMiddleTopRadius();
      p["middleBulge"]    = dock->ftMiddleBulge();
      p["coneHeight"]     = dock->ftConeHeight();
    }
    else if ( type == "TwoGableHouses" )
    {
      p["length1"]     = dock->tgLength1();
      p["length2"]     = dock->tgLength2();
      p["width"]      = dock->tgWidth();
      const double wallH = dock->tgWallHeight();
      const double roofH = dock->tgRoofHeight();
      const double totalH = wallH + roofH;
      p["totalHeight"] = totalH;
      p["wallRatio"] = totalH > 1e-6 ? wallH / totalH : 0.7;
      p["angle"]      = dock->tgAngle();
      p["ridgeRatio"] = dock->tgRidgeRatio();
    }
    else if ( type == "TriPrismPyramid" )
    {
      p["leg"]          = dock->triPrismPyramidLeg();
      p["baseSide"]     = dock->triPrismPyramidBase();
      p["totalHeight"]  = dock->triPrismPyramidHeight();
      p["pyramidRatio"] = dock->triPrismPyramidRatio();
    }

    return p;
}
